const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..');
function scripts(file){return [...fs.readFileSync(path.join(root,file),'utf8').matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)].filter(m=>!m[1].includes('src=')&&!m[1].includes('application/ld+json')).map(m=>m[2]);}
function element(props={}){const classes=new Set();return Object.assign({value:'',checked:false,hidden:false,disabled:false,style:{},listeners:{},attrs:{},addEventListener(e,f){this.listeners[e]=f},setAttribute(k,v){this.attrs[k]=v},focus(){},classList:{toggle(k,force){const add=force===undefined?!classes.has(k):force;add?classes.add(k):classes.delete(k);return add},contains:k=>classes.has(k)}},props);}
const flush=()=>new Promise(r=>setImmediate(r));
function signup(mode){let stored=0;const ids={};for(const k of ['optinForm','phone','phoneError','submitBtn','successState','saveError','fullName','consent'])ids[k]=element();ids.phone.value='9045550123';ids.fullName.value='Test Only';ids.consent.checked=true;
const firestore=()=>({collection:()=>({add:()=>{stored++;return mode==='reject'?Promise.reject(Error('offline')):Promise.resolve();}})});firestore.FieldValue={serverTimestamp:()=>123};const context={document:{getElementById:id=>ids[id]},console:{warn(){},error(){}},firebase:mode==='missing'?undefined:{apps:[{}],firestore}};vm.runInNewContext(scripts('text-signup.html')[0],context);return{ids,submit:()=>ids.optinForm.listeners.submit({preventDefault(){}}),stored:()=>stored};}
test('all modified page scripts parse',()=>{for(const file of ['index.html','catalog.html','door-finder.html','text-signup.html'])for(const source of scripts(file))new vm.Script(source,{filename:file});});
test('signup success requires a confirmed save',async()=>{const h=signup('ok');h.submit();assert.equal(h.ids.optinForm.style.display,undefined);await flush();assert.equal(h.stored(),1);assert.equal(h.ids.optinForm.style.display,'none');assert.equal(h.ids.successState.style.display,'block');});
test('failed signup preserves inputs and enables retry',async()=>{const h=signup('reject');h.submit();await flush();assert.notEqual(h.ids.successState.style.display,'block');assert.equal(h.ids.saveError.hidden,false);assert.equal(h.ids.submitBtn.disabled,false);assert.equal(h.ids.fullName.value,'Test Only');h.submit();await flush();assert.equal(h.stored(),2);});
test('missing SDK gives an error instead of success or an exception',()=>{const h=signup('missing');h.submit();assert.equal(h.ids.saveError.hidden,false);assert.equal(h.ids.submitBtn.disabled,false);assert.equal(h.stored(),0);});
test('invalid phone cannot be submitted',()=>{const h=signup('ok');h.ids.phone.value='123';h.submit();assert.equal(h.stored(),0);assert.equal(h.ids.phoneError.style.display,'block');});
test('catalog combines text search and category and announces no results',()=>{const cards=[element({dataset:{cat:'exterior'},textContent:'36 fiberglass craftsman $599'}),element({dataset:{cat:'interior'},textContent:'30 shaker wood $135'})];const tabs=['all','exterior','interior'].map(filter=>element({dataset:{filter}}));const ids={'catalog-search':element(),'catalog-results':element(),'catalog-empty':element()};const doc={querySelectorAll:s=>s==='.catalog-card'?cards:s==='.filter-tab'?tabs:[],getElementById:id=>ids[id]};vm.runInNewContext(scripts('catalog.html').find(s=>s.includes('function filterCatalog')), {document:doc,navigator:{userAgent:'test'},URLSearchParams});ids['catalog-search'].value='36 craftsman';ids['catalog-search'].listeners.input();assert.equal(cards[0].classList.contains('hidden'),false);assert.equal(cards[1].classList.contains('hidden'),true);tabs[2].listeners.click();assert.equal(ids['catalog-empty'].hidden,false);assert.equal(ids['catalog-results'].textContent,'Showing 0 of 2 doors');ids['catalog-search'].value='';ids['catalog-search'].listeners.input();assert.equal(cards[1].classList.contains('hidden'),false);assert.equal(tabs[2].attrs['aria-pressed'],'true');});
test('every catalog item has a distinct SMS inquiry and a working image path',()=>{const html=fs.readFileSync(path.join(root,'catalog.html'),'utf8');const cards=[...html.matchAll(/<article\b[\s\S]*?<\/article>/g)];assert.equal(cards.length,26);for(const [i,match] of cards.entries()){const card=match[0],href=card.match(/class="catalog-cta catalog-text" href="([^"]+)"/)[1];assert(href.startsWith('sms:9044035261?body='));assert(decodeURIComponent(href).includes('#door-'+(i+1)));}assert(!html.includes('data:image/jpeg;base64'));for(const m of html.matchAll(/src="(images\/catalog\/[^\"]+)"/g))assert(fs.existsSync(path.join(root,m[1])));});
test('old links lead to working pages and 404 offers inventory',()=>{assert(fs.readFileSync(path.join(root,'door-swing.html'),'utf8').includes('/tools/door-swing.html'));assert(fs.readFileSync(path.join(root,'stock/index.html'),'utf8').includes('/catalog.html'));assert(!fs.readFileSync(path.join(root,'door-finder.html'),'utf8').includes('norwoodsupply.com/stock'));assert(fs.readFileSync(path.join(root,'404.html'),'utf8').includes('Page Not Found'));});
